# Generated by Django 5.1.3 on 2024-11-14 15:34

from django.db import migrations, models

"YAZARLARI VERİTABANINDA OLUŞTURDUK"
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
